FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BookHub.csproj", "."]
RUN dotnet restore "BookHub.csproj"
COPY . .
RUN dotnet build "BookHub.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BookHub.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://*:8080
ENTRYPOINT ["dotnet", "BookHub.dll"]